"use strict";
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
Object.defineProperty(exports, "__esModule", { value: true });
var define_middlewares_1 = require("../utils/define-middlewares");
var middlewares_1 = require("./admin/api-keys/middlewares");
var middlewares_2 = require("./admin/campaigns/middlewares");
var middlewares_3 = require("./admin/claims/middlewares");
var middlewares_4 = require("./admin/collections/middlewares");
var middlewares_5 = require("./admin/currencies/middlewares");
var middlewares_6 = require("./admin/customer-groups/middlewares");
var middlewares_7 = require("./admin/customers/middlewares");
var middlewares_8 = require("./admin/draft-orders/middlewares");
var middlewares_9 = require("./admin/exchanges/middlewares");
var middlewares_10 = require("./admin/fulfillment-providers/middlewares");
var middlewares_11 = require("./admin/fulfillment-sets/middlewares");
var middlewares_12 = require("./admin/fulfillments/middlewares");
var middlewares_13 = require("./admin/inventory-items/middlewares");
var middlewares_14 = require("./admin/invites/middlewares");
var middlewares_15 = require("./admin/notifications/middlewares");
var middlewares_16 = require("./admin/order-edits/middlewares");
var middlewares_17 = require("./admin/orders/middlewares");
var middlewares_18 = require("./admin/payment-collections/middlewares");
var middlewares_19 = require("./admin/payments/middlewares");
var middlewares_20 = require("./admin/price-lists/middlewares");
var middlewares_21 = require("./admin/price-preferences/middlewares");
var middlewares_22 = require("./admin/product-categories/middlewares");
var middlewares_23 = require("./admin/product-tags/middlewares");
var middlewares_24 = require("./admin/product-types/middlewares");
var middlewares_25 = require("./admin/product-variants/middlewares");
var middlewares_26 = require("./admin/products/middlewares");
var middlewares_27 = require("./admin/promotions/middlewares");
var middlewares_28 = require("./admin/refund-reasons/middlewares");
var middlewares_29 = require("./admin/regions/middlewares");
var middlewares_30 = require("./admin/reservations/middlewares");
var middlewares_31 = require("./admin/return-reasons/middlewares");
var middlewares_32 = require("./admin/returns/middlewares");
var middlewares_33 = require("./admin/sales-channels/middlewares");
var middlewares_34 = require("./admin/shipping-options/middlewares");
var middlewares_35 = require("./admin/shipping-profiles/middlewares");
var middlewares_36 = require("./admin/stock-locations/middlewares");
var middlewares_37 = require("./admin/stores/middlewares");
var middlewares_38 = require("./admin/tax-rates/middlewares");
var middlewares_39 = require("./admin/tax-regions/middlewares");
var middlewares_40 = require("./admin/tax-providers/middlewares");
var middlewares_41 = require("./admin/uploads/middlewares");
var middlewares_42 = require("./admin/users/middlewares");
var middlewares_43 = require("./admin/views/[entity]/configurations/middlewares");
var middlewares_44 = require("./admin/views/[entity]/columns/middlewares");
var middlewares_45 = require("./admin/workflows-executions/middlewares");
var middlewares_46 = require("./auth/middlewares");
var middlewares_47 = require("./hooks/middlewares");
var middlewares_48 = require("./store/carts/middlewares");
var middlewares_49 = require("./store/collections/middlewares");
var middlewares_50 = require("./store/currencies/middlewares");
var middlewares_51 = require("./store/customers/middlewares");
var middlewares_52 = require("./store/middlewares");
var middlewares_53 = require("./store/orders/middlewares");
var middlewares_54 = require("./store/payment-collections/middlewares");
var middlewares_55 = require("./store/payment-providers/middlewares");
var middlewares_56 = require("./store/product-categories/middlewares");
var middlewares_57 = require("./store/product-tags/middlewares");
var middlewares_58 = require("./store/product-types/middlewares");
var middlewares_59 = require("./store/products/middlewares");
var middlewares_60 = require("./store/regions/middlewares");
var middlewares_61 = require("./store/return-reasons/middlewares");
var middlewares_62 = require("./store/shipping-options/middlewares");
var middlewares_63 = require("./admin/shipping-option-types/middlewares");
exports.default = (0, define_middlewares_1.defineMiddlewares)(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray(__spreadArray([], middlewares_52.storeRoutesMiddlewares, true), middlewares_6.adminCustomerGroupRoutesMiddlewares, true), middlewares_7.adminCustomerRoutesMiddlewares, true), middlewares_27.adminPromotionRoutesMiddlewares, true), middlewares_2.adminCampaignRoutesMiddlewares, true), middlewares_48.storeCartRoutesMiddlewares, true), middlewares_51.storeCustomerRoutesMiddlewares, true), middlewares_48.storeCartRoutesMiddlewares, true), middlewares_49.storeCollectionRoutesMiddlewares, true), middlewares_56.storeProductCategoryRoutesMiddlewares, true), middlewares_57.storeProductTagRoutesMiddlewares, true), middlewares_58.storeProductTypeRoutesMiddlewares, true), middlewares_55.storePaymentProvidersMiddlewares, true), middlewares_62.storeShippingOptionRoutesMiddlewares, true), middlewares_54.storePaymentCollectionsMiddlewares, true), middlewares_53.storeOrderRoutesMiddlewares, true), middlewares_46.authRoutesMiddlewares, true), middlewares_45.adminWorkflowsExecutionsMiddlewares, true), middlewares_32.adminReturnRoutesMiddlewares, true), middlewares_60.storeRegionRoutesMiddlewares, true), middlewares_29.adminRegionRoutesMiddlewares, true), middlewares_32.adminReturnRoutesMiddlewares, true), middlewares_42.adminUserRoutesMiddlewares, true), middlewares_14.adminInviteRoutesMiddlewares, true), middlewares_38.adminTaxRateRoutesMiddlewares, true), middlewares_39.adminTaxRegionRoutesMiddlewares, true), middlewares_1.adminApiKeyRoutesMiddlewares, true), middlewares_47.hooksRoutesMiddlewares, true), middlewares_37.adminStoreRoutesMiddlewares, true), middlewares_5.adminCurrencyRoutesMiddlewares, true), middlewares_50.storeCurrencyRoutesMiddlewares, true), middlewares_26.adminProductRoutesMiddlewares, true), middlewares_19.adminPaymentRoutesMiddlewares, true), middlewares_20.adminPriceListsRoutesMiddlewares, true), middlewares_21.adminPricePreferencesRoutesMiddlewares, true), middlewares_13.adminInventoryRoutesMiddlewares, true), middlewares_4.adminCollectionRoutesMiddlewares, true), middlewares_34.adminShippingOptionRoutesMiddlewares, true), middlewares_8.adminDraftOrderRoutesMiddlewares, true), middlewares_33.adminSalesChannelRoutesMiddlewares, true), middlewares_36.adminStockLocationRoutesMiddlewares, true), middlewares_63.adminShippingOptionTypeRoutesMiddlewares, true), middlewares_24.adminProductTypeRoutesMiddlewares, true), middlewares_23.adminProductTagRoutesMiddlewares, true), middlewares_41.adminUploadRoutesMiddlewares, true), middlewares_11.adminFulfillmentSetsRoutesMiddlewares, true), middlewares_15.adminNotificationRoutesMiddlewares, true), middlewares_17.adminOrderRoutesMiddlewares, true), middlewares_30.adminReservationRoutesMiddlewares, true), middlewares_22.adminProductCategoryRoutesMiddlewares, true), middlewares_35.adminShippingProfilesMiddlewares, true), middlewares_12.adminFulfillmentsRoutesMiddlewares, true), middlewares_10.adminFulfillmentProvidersRoutesMiddlewares, true), middlewares_59.storeProductRoutesMiddlewares, true), middlewares_61.storeReturnReasonRoutesMiddlewares, true), middlewares_31.adminReturnReasonRoutesMiddlewares, true), middlewares_3.adminClaimRoutesMiddlewares, true), middlewares_28.adminRefundReasonsRoutesMiddlewares, true), middlewares_9.adminExchangeRoutesMiddlewares, true), middlewares_25.adminProductVariantRoutesMiddlewares, true), middlewares_40.adminTaxProviderRoutesMiddlewares, true), middlewares_16.adminOrderEditRoutesMiddlewares, true), middlewares_18.adminPaymentCollectionsMiddlewares, true), middlewares_43.viewConfigurationRoutesMiddlewares, true), middlewares_44.columnRoutesMiddlewares, true));
